export enum Type {
  Grass = 'grass',
  Fire = 'fire',
  Water = 'water',
  Electric = 'electric',
  Bug = 'bug',
  Rock = 'rock',
  Ground = 'ground',
  Fighting = 'fighting',
  Ice = 'ice',
  Poison = 'poison',
  Flying = 'flying',
  Fairy = 'fairy',
  Dark = 'dark',
  Steel = 'steel',
  Normal = 'normal',
  Psychic = 'psychic',
  Ghost = 'ghost',
  Dragon = 'dragon'
}
